silsondb placement work/orders/urls.py
from django.conf.urls import include, url
from django.views.generic import ListView, DetailView
from . import views
from .models import Mask
from .models import Wafer
from .models import Process_record
from .models import Jobb
from .views import WaferListing, WaferDetail, WaferCreate, WaferUpdate
from .views import MaskListing, MaskDetail, MaskCreate, MaskUpdate
from .views import Process_recordListing, Process_recordDetail, Process_recordCreate, Process_recordUpdate
from .views import JobbListing, JobbDetail, JobbCreate, JobbUpdate
app_name = 'orders'
urlpatterns = [
    
   url(r'^$', views.home),
   url(r'^wafer/$', WaferListing.as_view(), name ='wafer_list'),
    url(r'^wafer/create/$',WaferCreate.as_view(), name ='create'),
    url(r'^wafer/(?P<pk>\d+)/$',WaferDetail.as_view(), name ='wafer_detail'),
     url(r'^wafer/(?P<pk>\d+)/update/$', WaferUpdate.as_view(), name='update'),

    url(r'^mask/$', MaskListing.as_view(), name ='mask_list'),
    url(r'^mask/create/$',MaskCreate.as_view(), name ='create'), 
    url(r'^mask/(?P<pk>\d+)/$',MaskDetail.as_view(), name ='mask_detail'),
    url(r'^mask/(?P<pk>\d+)/update/$', MaskUpdate.as_view(), name='update'),  
    
    url(r'^job/$', JobbListing.as_view(), name ='jobb_list'),
    url(r'^job/create/$',JobbCreate.as_view(), name ='create'), 
    url(r'^job/(?P<pk>\d+)/$',JobbDetail.as_view(), name ='jobb_detail'),
    url(r'^job/(?P<pk>\d+)/update/$', JobbUpdate.as_view(), name='update'), 
     url(r'^job/search/$', views.jobb_list),
    url(r'^job/search/(?P<pk>\d+)/$',views.jobb_search),
     	
    url(r'^select2/', include('django_select2.urls')),

    url(r'^prs/$', Process_recordListing.as_view(), name ='process_record_list'),
    url(r'^prs/create/$',Process_recordCreate.as_view(), name ='create'),    
    url(r'^prs/(?P<pk>\d+)/$',Process_recordDetail.as_view(), name ='process_record_detail'),
    url(r'^prs/(?P<pk>\d+)/update/$', Process_recordUpdate.as_view(), name='update'),
     url(r'^prs/search/$', views.process_record_list),   
   url(r'^prs/search/(?P<pk>\d+)/$',views.process_record_search), 
]

silsondb placement work/silsondb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^jobs/', include('orders.urls')),
    url(r'^', include('silson.urls')),
    
]

silsondb placement work/orders/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
from silson.models import Customer, User, Affiliation
import datetime

class Wafer(models.Model):
    reference=models.CharField(max_length=15)
    coating=models.CharField(max_length=12)
    coating_thickness=models.IntegerField(default=0)
    diameter=models.FloatField(default=0)
    silicon_date=models.DateField()
    box_no=models.IntegerField(default=0)
    no_of_wafers=models.IntegerField(default=0)
    stress=models.CharField(max_length=5)
    polish=models.CharField(max_length=8)
    wafer_thickness=models.IntegerField(default=0)
    membrane_thickness=models.IntegerField(default=0)
    comment=models.TextField(blank=True)

    def __str__(self):            
        return self.reference

class Mask(models.Model):
    reference=models.CharField(max_length=12)
    membrane_size=models.FloatField(max_length= 10)
    wafer_dia=models.IntegerField(default=0)
    wafer_thickness=models.IntegerField(default=0)
    number_available= models.IntegerField(default=0)
    frame_size=models.FloatField(default=0)
    comment=models.TextField(blank=True)
    def save(self, force_insert=False, force_update=False):
        self.reference =self.reference.upper()
        super(Mask, self).save(force_insert, force_update)
    def __str__(self):            
        return self.reference

class Jobb(models.Model):
    job_No= models.CharField(max_length= 10)
    customer=models.ForeignKey(Customer)
    p_order_no = models.CharField(max_length=10)
    p_order_date = models.DateField(blank=True)
    po_acknowledged = models.DateField(blank=True)
    ship_b=(('FedEx','FedEx'),('DHL', 'DHL'),('DPD', 'DPD'))
    ship_by=models.CharField(max_length=7,choices= ship_b)  
    purchase_contact= models.ForeignKey(User)
    end_user = models.CharField(max_length=12)
    date_received=models.DateField(blank=True)
    disp_date= models.DateField(blank=True)
    disp_advised=models.DateField(blank=True)
    POD_Date = models.DateField(blank=True)
    invoice_No =models.CharField(max_length=10, blank=True)
    invoice_Date=models.DateField(blank=True)
    payment_received=models.DateField(blank=True)
    comments=models.TextField(blank=True)
    def __str__(self):
        return self.job_No

class Process_record(models.Model):
    sheet_No=models.CharField(max_length=10)
    job_No= models.ForeignKey(Jobb)
    customer=models.ForeignKey(Customer)
    job_Date= models.DateField()
    number_required=models.IntegerField(default=0)
    mask_ref=models.ForeignKey(Mask)
    wafer_ref=models.ForeignKey(Wafer)
    membrane_thickness=models.IntegerField(default=0)
    frame_size=models.FloatField(default=0)
    frame_added_to_stock=models.IntegerField(default=0)    
    apertures=models.TextField(blank=True)
    comment=models.TextField(blank=True)
    def __str__(self):
        return self.sheet_No
# Create your models here.

silsondb placement work/orders/forms.py
from django.forms import ModelForm


from django.forms import inlineformset_factory

from .models import Jobb, Process_record


class JobbForm(ModelForm):
    class Meta:
        model = Jobb
        fields='__all__'
        
class Process_recordForm(ModelForm):
    class Meta:
        model = Process_record
        fields='__all__'
Process_recordFormSet = inlineformset_factory(Jobb, Process_record, extra=0, min_num=1, fields=('__all__'))

silsondb placement work/orders/views.py
from django.shortcuts import get_object_or_404, render, render_to_response, redirect
from django.template import loader, context
from django.http import HttpResponseRedirect,HttpResponse,HttpResponsePermanentRedirect
from django.core.urlresolvers import reverse
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from .models import Wafer
from .models import Mask
from .models import Process_record
from .models import Jobb
import datetime
import django_filters
from django.db.models import Q
from django.forms import inlineformset_factory
from .forms import Process_recordFormSet, JobbForm
class FormsetMixin(object):
    object = None

    def get(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def post(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def get_formset_class(self):
        return self.formset_class

    def get_formset(self, formset_class):
        return formset_class(**self.get_formset_kwargs())

    def get_formset_kwargs(self):
        kwargs = {
            'instance': self.object
        }
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def form_valid(self, form, formset):
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        return redirect(self.object.get_absolute_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form, formset=formset))
def home(request):
    return render(request, 'orders/home.html')
class MaskListing(ListView):
     model = Mask
class MaskCreate(CreateView):
    model = Mask
    success_url ='/jobs/mask'
    fields= ['reference','membrane_size','wafer_dia','wafer_thickness','number_available','frame_size','comment']
class MaskDetail(DetailView):
    model = Mask
class MaskUpdate(UpdateView):
    model = Mask
    fields= ['reference','membrane_size','wafer_dia','wafer_thickness','number_available','frame_size','comment']
    def get_success_url(self):
         return reverse('orders:mask_detail', kwargs={
             'pk': self.object.pk,
         })

class WaferListing(ListView):
     model = Wafer
class WaferCreate(CreateView):
    model = Wafer
    success_url ='/jobs/wafer'
    fields= ['reference','coating','coating_thickness','silicon_date','diameter','box_no','no_of_wafers','stress','polish','membrane_thickness','comment']
class WaferDetail(DetailView):
    model = Wafer
class WaferUpdate(UpdateView):
    model = Wafer
    fields= ['reference','coating','coating_thickness','silicon_date','diameter','box_no','no_of_wafers','stress','polish','membrane_thickness','comment']
    def get_success_url(self):
         return reverse('orders:wafer_detail', kwargs={
             'pk': self.object.pk,
         })
class JobbListing(ListView):
     model = Jobb
class JobbCreate(FormsetMixin,CreateView):
    model = Jobb
    success_url ='/jobs/job'
    form_class=JobbForm
    formset_class = Process_recordFormSet
    
    
class JobbDetail(DetailView):
    model = Jobb
class JobbUpdate(FormsetMixin,UpdateView):
    model = Jobb
    is_update_view =True
    form_class=JobbForm
    formset_class= Process_recordFormSet
    #fields= ['job_No','customer','p_order_no','p_order_date','po_acknowledged','ship_by','purchase_contact','end_user','date_received','disp_date','disp_advised','POD_Date','invoice_No','invoice_Date','payment_received','comments']
    def get_success_url(self):
         return reverse('orders:jobb_detail', kwargs={
             'pk': self.object.pk,
         })
class JobbFilter(django_filters.FilterSet):
    customer = django_filters.CharFilter(lookup_expr='icontains')
    purchase_contact = django_filters.CharFilter(lookup_expr='icontains')

    class Meta:
        model = Jobb
        fields = ['customer','purchase_contact']

def jobb_list(request):
    query = request.GET['q']
    f = JobbFilter(request.GET, 
      queryset=Jobb.objects.all().filter(Q(customer__full_Name__icontains= query)|Q(purchase_contact__name__icontains=query)).distinct())
    return render(request, 'orders/jobb_search.html',{'filter' :f})


def jobb_search(request,jobb_id):
   return render_to_response('jobb_detail.html',{'job':Jobb.objects.get(pk=jobb_id)}) 

class Process_recordListing(ListView):
     model = Process_record

class Process_recordCreate(CreateView):
    model = Process_record
    success_url ='/jobs/prs'
    fields= ['sheet_No','job_No','customer','job_Date','number_required','mask_ref','wafer_ref','membrane_thickness','frame_size','frame_added_to_stock','apertures','comment']
class Process_recordDetail(DetailView):
    model = Process_record
class Process_recordUpdate(UpdateView):
    model = Process_record
    fields= ['sheet_No','job_No','customer','job_Date','number_required','mask_ref','wafer_ref','membrane_thickness','frame_size','frame_added_to_stock','apertures','comment']
    def get_success_url(self):
         return reverse('orders:process_record_detail', kwargs={
             'pk': self.object.pk,
         })
class Process_recordFilter(django_filters.FilterSet):
    customer = django_filters.CharFilter(lookup_expr='icontains')
    class Meta:
        model = Process_record
        fields = ['customer']

def process_record_list(request):
    query = request.GET['q']
    f = Process_recordFilter(request.GET, 
      queryset=Process_record.objects.all().filter(customer__full_Name__icontains= query).distinct())
    return render(request, 'orders/process_record_search.html',{'filter' :f})


def process_record_search(request,process_record_id):
   return render_to_response('process_record_detail.html',{'process_record':Process_record.objects.get(pk=process_record_id)}) 

silsondb placement work/orders/templates/orders/home.html
{% extends "silson/base.html" %}
 {%load staticfiles %}

{% block content %}
<div class="breadcrumbs">
<a href="/">Home</a>
&rsaquo;Jobs
</div>

<h1 >JOBS</h1>  
<div class ="list-group">
    
     
   <a style="font-size: 20px" href = "mask"  class="list-group-item" >Mask</a>
<a style="font-size: 20px" href = "wafer"  class="list-group-item" >Wafer</a>
   <a style="font-size: 20px" href = "prs"  class="list-group-item" >Process Record</a>
<a style="font-size: 20px" href = "job"  class="list-group-item" >Job</a>

    </div>
 
{% endblock %}

silsondb placement work/orders/templates/orders/jobb_detail.html
{% extends "silson/base.html" %}
  {%load staticfiles %}
{% block content %}

<div class="breadcrumbs">
<a href="/">Home</a>
&rsaquo; <a href="/jobs/">Jobs</a>
&rsaquo; <a href="/jobs/job/">Job</a>
&rsaquo; {{object.job_No}}
</div>

<nav class="navbar navbar-default">
<div class="container-fluid">
    <div class="navbar">
    <h2> <a href = "/jobs/job">Job</a></h2>
    <ul class="nav navbar-nav navbar-right">
        <ul class="object-tools">    
    <li> <a href="/jobs/job/create"  class="addlink">Create Job </a></li>  
        <div class="input-group"> 
       

      </div></ul>
    </ul>
</div>
   </div>
</nav>


<div>
<fieldset class="module aligned ">
    
    
    
        <div class="form-row field-name">
            
            <h2>Job Detail</h2>  
                <div>
 
               
<p style="font-size: 20px">Job No: {{ jobb.job.No}}</p>
<p style="font-size: 20px"> Customer: {{ jobb.customer}}</p>
<h4 style = " font-size : 25px" >Customer Information</h4> 
<p style="font-size: 20px">Product Order No: {{ jobb.p_order_no}}</p>
<p style="font-size: 20px">Product Order Date: {{jobb.p_order_date}}</p>
<p style="font-size: 20px"> Product Order Acknowledged:{{jobb.po_acknowledged}}</p>
<p style="font-size: 20px">Ship By: {{jobb.ship_by}}</p>
<p style="font-size: 20px">Purchase Contact: {{jobb.purchase_contact}}</p>
<p style="font-size: 20px">End User: {{jobb.end_user}}</p>
<p style="font-size: 20px">Date Recieved: {{jobb.date_received}}</p>
<p style="font-size: 20px">Dispatch Date: {{jobb.disp_date}}</p>
<p style="font-size: 20px">Dispatch Advised: {{jobb.disp_advised}}</p>
<p style="font-size: 20px">POD Date: {{jobb.POD_Date}}</p>
<p style="font-size: 20px">Invoice No: {{ jobb.invoice_No}}</p>
<p style="font-size: 20px">Invoice Date: {{jobb.invoice_Date}}</p>
<p style="font-size: 20px">Payment Received: {{jobb.payment_received}}</p>
<p style="font-size: 20px">Comments: {{jobb.comments}}</p>

<table class="table table-striped">
{% for process_record in object.process_record_set.all %}

<p><a style="font-size: 15px" href="/jobs/prs/{{process_record.id}}">PRSheet No:{{ process_record.sheet_No }}</a></p>   
<p style="font-size: 15px" >Job Date: {{process_record.job_Date}} </p>  
<p style="font-size: 15px" >Number Required: {{process_record.number_required}} </p>  
<p style="font-size: 15px" >Mask Ref: {{process_record.mask_ref}} </p>  
<p style="font-size: 15px" >Wafer Ref: {{process_record.wafer_ref}} </p>  
<p style="font-size: 15px" >Membrame Thickness: {{process_record.membrame_thickness}} </p>  
<p style="font-size: 15px" >Frame Size: {{process_record.frame_size}} </p>  
<p style="font-size: 15px" >Frame added to stock: {{process_record.frame_added_to_stock}} </p>  
<p style="font-size: 15px" >Comment: {{process_record.comment}} </p>



    {% endfor %}
</table>
</div>
            
        </div>
    
</fieldset>

<div class="submit-row">
 <a href="update" class="btn btn-info" role="button"> UPDATE</a>
</div>
</div>


{% endblock %}
<h4 style = " font-size : 25px" >Items Required</h4> 
<p style="font-size: 20px">Number required: {{job_.no_required}}</p>
<p style="font-size: 20px">Frame Size: {{job_.frame_size}}</p>
<p style="font-size: 20px">Frame Thickness: {{job_.frame_thickness}}</p>
<p style="font-size: 20px">Membrane Size: {{job_.membrane_size}}</p>
<p style="font-size: 20px">Membrane Thickness: {{job_.membrane_thickness}}</p>
<p style="font-size: 20px">Product Codes: {{job_.product_codes}}</p>
<p style="font-size: 20px">Stock No: {{job_.stock_no}}</p>
<p style="font-size: 20px">Process Record Sheet: {{job_.prs}}</p>
<p style="font-size: 20px">Used: {{job_.used}}</p>
<p style="font-size: 20px">Quality: {{job_.quality}}</p>
<p style="font-size: 20px">Product Code Updated: {{job_.product_code_updated}}</p>

silsondb placement work/orders/templates/orders/manage.html
<!DOCTYPE html>
<html lang="en">
	<head>
        <meta charset="utf-8" />
        <title>TEST</title>
    </head>
	<body>

     {% load crispy_forms_tags %} 
     <form method="post" action="" class="">
        
        {% crispy form   %}
        {% crispy formset formset.form.helper %}

        <input class="submit" type="submit" value="Submit data">
        
    </form>
    
    </body>
</html>

silsondb placement work/orders/templates/orders/mask_base.html
{% load staticfiles %}


<style>
 .breadcrumb {
     background-color: #8fa2bb;
     border-radius: 0;
     -moz-border-radius: 0;
     -webkit-border-radius: 0;
     -o-border-radius: 0;
}

.breadcrumb a {
     color: #4d74a9;
}

.breadcrumb a:hover {
     text-decoration: none;
}

.breadcrumb > .active {
     color:#133563;
}


</style>

silsondb placement work/orders/templates/orders/mask_form.html
{% extends "silson/base.html" %}
 {% block content %}
  <div class="breadcrumbs">
<a href="/">Home</a>
&rsaquo; <a href="/jobs/">Jobs</a>
&rsaquo; <a href="/jobs/mask/">Masks</a>
&rsaquo; Create Mask
</div>

<nav class="navbar navbar-default">
<div class="container-fluid">
    <div class="navbar">
    <h2> <a href = "/jobs/mask">Mask</a></h2>
    <ul class="nav navbar-nav navbar-right">
        <ul class="object-tools">    
    <li> <a href="/jobs/mask/create"  class="addlink">Create Mask </a></li>  
        <div class="input-group"> 
       
      </div></ul>
    </ul>
</div>
   </div>
</nav>
<div>
<form action="" method="post">
<input type='hidden' name='csrfmiddlewaretoken' value='tJ1rwEyvLdbSiPY1pOBK0DZD4UiAzhx3' />
 <h2>Add Mask</h2>  
<fieldset class="module aligned ">
    {% csrf_token %}
    {{ form.as_p }}  
</fieldset>
<div class="submit-row">
<input type="submit" value="Save" class="default" name="_save" />
<input type="submit" value="Save and add another" name="_addanother" />
<input type="submit" value="Save and continue editing" name="_continue" />
</div>


</form></div>

   {% endblock %}

silsondb placement work/orders/templates/orders/mask_search.html
{% extends "silson/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="breadcrumbs">
<a href="/">Home</a>
&rsaquo; <a href="/jobs/">Jobs</a>
&rsaquo; <a href="/jobs/mask/">Mask</a>
&rsaquo; Search Result

</div>

<nav class="navbar navbar-default">
<div class="container-fluid">
    <div class="navbar">
    <h2> <a href = "/jobs/mask">Mask</a></h2>
    <ul class="nav navbar-nav navbar-right">
        <ul class="object-tools">    
    <li> <a href="/jobs/mask/create"  class="addlink">Create Mask </a></li>  
        <div class="input-group"> 
       

      </div></ul>
    </ul>
</div>
   </div>
</nav>


<h1>Searched for: {{ query }}</h1>
 
{% for obj in filter %}
<li><a style = " font-size : 20px"  href = "jobs/mask/{{obj.id}}" >{{obj.reference}}</a></li>

</ul>  {% endfor %}
 
{% endblock %}

silsondb placement work/orders/templates/orders/oljob.html
{% extends "silson/base.html" %}
  {%load staticfiles %}
{% block content %}
{% block bottom_script %}{{ block.super }}
    <script type="text/html" id="process_record-template">
    <div id="process-record-__prefix__">
        {{ formset.empty_form }}
    </div>
    </script>
    <script>
    $(function() {
        $('.add-process-record').click(function(ev){
            ev.preventDefault();
            var count = parseInt($('#process_record_id_set-TOTAL_FORMS').attr('value'), 10);
            var tmplMarkup = $('#process_record-template').html();
            var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count)
            console.log(compiledTmpl);
            $('div.process_record').append(compiledTmpl);
            $('#process_record_id_set-TOTAL_FORMS').attr('value', count + 1);
        });
    });
    </script>
{% endblock bottom_script %}
{% block base_content %}
<form action="." method="post">
    {{ formset.management_form }}
    {% csrf_token %}

    <legend>JOB</legend>
    <div class="Jobb">
    {{ form }}
    </div>

    <legend>
        <div class="pull-right"><a href="#" class="btn btn-inverse add-process_record"><i class="icon-plus icon-white"></i> Add Process Record</a></div>
        Process Record Sheet
    </legend>
    <div class="process_record form-inline">
        {% for form in formset %}
            {{ form }}
        {% endfor %}
    </div>
  <div class="form-actions">
     <button type="submit" class="btn btn-primary">Save</button>
   </div>
 </form>

{% endblock base_content %}
{% endblock %}

silsondb placement work/orders/templates/orders/process_record_base.html
{% load staticfiles %}
<style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #D5D8DC;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;}
    }
  </style>
<div class="container-fluid">
<div class="row content">
<div class ="col-sm-3 sidenav">
<h6> <a href = "/jobs">JOBS</a><h6>
<h2> 
<a href = "/jobs/prs">Process Record</a></h2>

<li><a href="/jobs/prs/create" class="btn btn-default navbar-btn" role="button">CREATE</a></li>
<br>
    <div class="input-group">
       <form method="get" action="search/">
          
<label for="id_q">Search:</label>
           <input type="text" name="q" id="id_q"/>
           <input type="submit" value="Search"/>
        </form>
    
        </span>
      </div>
    </div>

silsondb placement work/orders/templates/orders/process_record_form.html
{% extends "silson/base.html" %}
 {% block content %}
   <div class="breadcrumbs">
<a href="/">Home</a>
&rsaquo; <a href="/jobs/">Jobs</a>
&rsaquo; <a href="/jobs/prs/">Process Record</a>
&rsaquo; Create Process Record Sheet
</div>

<nav class="navbar navbar-default">
<div class="container-fluid">
    <div class="navbar">
    <h2> <a href = "/jobs/prs"> Process Record</a></h2>
    <ul class="nav navbar-nav navbar-right">
        <ul class="object-tools">    
    <li> <a href="/jobs/prs/create"  class="addlink">Create Process Record Sheet </a></li>  
        <div class="input-group"> 
       

      </div></ul>
    </ul>
</div>
   </div>
</nav>
<div>
<form action="" method="post">
<input type='hidden' name='csrfmiddlewaretoken' value='tJ1rwEyvLdbSiPY1pOBK0DZD4UiAzhx3' />
 <h2>New Process Record Sheet</h2>  

<button> <a class="related-widget-wrapper-link change-related" id="add_id_added_by"
            href="/jobs/mask/create/?_to_field=id&amp;_popup=1"
            title="Add another mask"role="button">New Mask</a></button>
<button> <a class="related-widget-wrapper-link change-related" id="add_id_added_by"
            href="/jobs/wafer/create/?_to_field=id&amp;_popup=1"
            title="Add another wafer"role="button">New Wafer</a></button>
<button> <a class="related-widget-wrapper-link change-related" id="add_id_added_by"
            href="/customer/create/?_to_field=id&amp;_popup=1"
            title="Add another customer"role="button">New Customer</a></button>
<fieldset class="module aligned ">
    {% csrf_token %}
    {{ form.as_p }}
  
</div>   
</fieldset>

<div class="submit-row">
<input type="submit" value="Save" class="default" name="_save" />
<input type="submit" value="Save and add another" name="_addanother" />
<input type="submit" value="Save and continue editing" name="_continue" />
</div>

</form></div>
   {% endblock %}

silsondb placement work/orders/templates/orders/process_record_list.html
{% extends "silson/base.html" %}
{% load static %}


{% block content %}
<div class="breadcrumbs">
<a href="/">Home</a>
&rsaquo; <a href="/jobs/">Jobs</a>
&rsaquo; Process Record Sheet
</div>

<nav class="navbar navbar-default">
<div class="container-fluid">
    <div class="navbar">
    <h3>  Select Process Record Sheet to View</h3>
    <ul class="nav navbar-nav navbar-right">
        <ul class="object-tools">    
    <li> <a href="/jobs/prs/create"  class="addlink">Create Process Record Sheet </a></li>  
        <div class="input-group"> 
       <form method="get" action="search/">          
    <label for="id_q">Search:</label>
           <input type="text" name="q" id="id_q"/>
           <input type="submit" value="Search"/>
    </form>

      </div></ul>
    </ul>
</div>
   </div>
</nav>

<div class="results">
<table class="table table-striped">
<thead>
<tr>
<th scope="col"  class="sortable column-sheet_No"> 
   <div class="text">Sheet No</div>
   <div class="clear"></div>
</th>
<th scope="col"  class="sortable column-job_No">
   <div class="text">Job No</div>
   <div class="clear"></div>
</th>
<th scope="col"  class="sortable column-customer">
   <div class="text">Customer</div>
   <div class="clear"></div>
</th>
<th scope="col"  class="sortable column-job_Date">
   <div class="text">Job Date</div>
   <div class="clear"></div>
</th>
<th scope="col"  class="sortable column-comment">
   <div class="text">Comment</div>
   <div class="clear"></div>
</th>
</tr>
</thead>
<tbody>
{% for process_record in process_record_list %}
<tr>
 <td><a style="font-size: 15px"  href = "{{process_record.id}}" >{{process_record.sheet_No}}</a></td>
 <td style="font-size: 15px" >{{process_record.job_No}}</td>
 <td style="font-size: 15px" >{{process_record.customer.full_Name}}</td>
 <td style="font-size: 15px" >{{process_record.job_Date}}</td>
 <td style="font-size: 15px" >{{process_record.comment}}</td>
</tr>

{% endfor %}
</tbody>
</table>
</div>
{% endblock %}